baseURL = '/'
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
enableEmoji = true
title = "Pranav's Blog"
copyright = 'Pranav Thandassery'
theme = 'hugo-theme-itheme'
paginate = 5
[params]
  defaultCover = 'https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg'
  email = 'pranav@potatoman.com'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/vexnity'
  [[params.blogroll]]
    name = 'idk what to put here'
    url = 'https://example.com/'
